#!/usr/bin/env bash
# A script that will tranfer a file between
# A server and a client

if [ $# -lt 4 ];
then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
	file=$1
	ip=$2
	username=$3
	ssh_key=$4

	scp -0 StrictHostKeyChecking=no "$ssh_key" "$file""$username"@"$ip":~/
fi
