#!/usr/bin/env bash
# script that install Nginx

sudo apt-get update
sudo apt-get install -y nginx

#configue nngix
echo 'hello World!' > /var/www/html/index.html

# restart nginx
service nginx start
