#!/usr/bin/env bash
# script that install Nginx

apt-get update
apt0get install -y nginx

#configue nginx
echo "server {
	listen 80;
	location / {
		echo 'Hello World!';
	}
}" > /etc/nginx/sites-available/default

# restart nginx
/etc/init.d/nginx restart
