#!/usr/bin/env bash
#configure nginx to return a http response
#custom header must be with a customise name
#value of custome http header
apt-get update
apt-get install -y nginx

sudo mkdir -p /var/www/html
sudo touch /var/www/html/index.html
echo "Hello World" > sudo /var/www/html/index.html
sudo touch /var/www/html/404.html
echo "Ceci n'est pas une page" > sudo /var/www/html/404.html

sudo printf %s "server {
    listen 80 default_server;
    listen [::]:80 default_server;
    add_header X-Served-By $HOSTNAME;
    root   /var/www/html;
    index  index.html index.htm;

    location /redirect_me {
        return 301 http://cuberule.com/;
    }

    error_page 404 /404.html;
    location /404 {
      root /var/www/html;
      internal;
    }
}" > sudo /etc/nginx/sites-available/default

sudo service nginx restart

