#!/usr/bin/env bash
# This scipt will print "Best school" n time and prints Hi for the second to last iteration

num=0
while [ $num -le 10 ];
do
	((num++))
	if [[ $num -eq 9 ]]
	then
		echo "bbb"
		continue
	if
		echo $num
done
