#!/usr/bin/env bash
#prints The "Best school" for 10 times and certain string on other iteration
i=1
while [ $i -le 10 ]
do
	if [ $i -eq 4 ];then
		echo "bad luck"
	elif [ $i -eq 8 ];then
		echo "good luck"
	else
		echo "Best School"
	fi
		(( i++ ))
done
