#!/usr/bin/env bash
# This script print int 1-20 and some word in between
i=1
while [ $i -le 20 ]
do
	case $i in
	5) echo "bad luck from china";;
	10) echo "bad luck from japan";;
	18) echo "bad luck from italy";;
esac
	echo "$i"
	(( i++ ))
done
