#!/usr/bin/env bash
#This script print a form of a clock 
#In minute and hours
#AURTHOR: Bubacarr
#Last Modified: 28-02-2023
h=0
while [ $h -le 12 ]
do
	echo "Hour: $h"
	m=1
	while [ $m -le 59 ]
	do
		echo $m
		(( m++ ))
	done
	
		(( h++ ))
done
